import Head from 'next/head'
import NavBar from './components/NavBar';
import First from './components/First';
import Second from './components/Second';
import Mechanical from './components/Mechanical';
import Electrical from "./components/Electrical";
import FireAlarm from './components/FireAlarm';
import FireVerification from './components/fireVerification';
import Boton from './components/Boton';
import Thir from './components/Thir';
import Four from './components/Four';
import One from './components/One';
import Two from './components/Two';
import Tres from './components/Tres';
import Cuatro from './components/Cuatro';
import Reviews from './components/Reviews';
import Ready from './components/Ready';
import Footer from './components/Footer';
import Atension from './components/Atension';

export default function Home() {
  return (
    <>
      <Head>
        <title>Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    <section className='Body'>
      <Atension />
      <First />
      <Second />
      <Mechanical />
      <Electrical />
      <FireAlarm />
      <FireVerification />
      <Boton />
      <Thir />
      <Four />
      <One />
      <Two />
      <Tres />
      <Cuatro />
      <Boton />
      <Reviews />
      <Ready />
      <Footer />
    </section>
    </>
  )
}
